name: Build React App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Download dependencies with npm
      run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - name: Run the tests and generate coverage report
      run: npm test -- --coverage
    - name: Adding coverage badge
      uses: demyanets/angular-coverage-badges-action@v1
      with:
        coverage-summary-path: ./coverage/coverage-summary.json
        github_token: ${{ secrets.GITHUB_TOKEN }}
